stat_svc
Anton-Phedorenko/java-explore-with-me pull request #3
Opened 2023-04-17 09:33 UTC by Anton-Phedorenko

2023-04-17 12:48 UTC, Anton-Phedorenko commented
Привет,Денис! Отправляю работу на проверку)

2023-04-17 20:09 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-04-17 20:09 UTC, FanaticFiz commented on ewm-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Версия и кодировка у нас на все сервисы одна, так что можно её описать один раз в родительском `pom`

2023-04-17 20:09 UTC, FanaticFiz commented on ewm-service/src/main/resources/application.properties
> +logging.level.org.springframework.web.client.RestTemplate=DEBUG
Пришло время перейти на YAML ? ))

2023-04-17 20:09 UTC, FanaticFiz commented on stats-server/src/main/java/ru/practicum/mapper/StatsMapper.java
> +    public static final DateTimeFormatter FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Сколько раз описал этот формат??

2023-04-17 20:09 UTC, FanaticFiz commented on stats-server/src/main/java/ru/practicum/repository/CustomDaoImpl.java
> +                sql = "select app, uri, count(ip) hits from stats " +
Оформляй SQL запросы. Пиши спец. слова в верхнем регистре: `CREATE`, `FROM`, `AND`

2023-04-17 20:09 UTC, FanaticFiz commented on stats-server/src/main/resources/schema.sql
> +    uri varchar(100),
100 символов - не маловато для URI ?

2023-04-20 22:16 UTC, Anton-Phedorenko commented on stats-server/src/main/resources/schema.sql
> +    uri varchar(100),
Да,надо бы побольше дать)

2023-04-20 22:16 UTC, Anton-Phedorenko commented on stats-server/src/main/java/ru/practicum/repository/CustomDaoImpl.java
> +                sql = "select app, uri, count(ip) hits from stats " +
хорошо

2023-04-20 22:32 UTC, Anton-Phedorenko commented on ewm-service/src/main/resources/application.properties
> +logging.level.org.springframework.web.client.RestTemplate=DEBUG
ну это классика:D

2023-04-20 22:36 UTC, Anton-Phedorenko commented
Привет, Денис! уже не терпится приступить ко второму этапу)

2023-04-21 10:32 UTC, FanaticFiz approved these changes

2023-04-26 09:23 UTC, merged