первая попытка
Anton-Phedorenko/java-explore-with-me pull request #4
Opened 2023-04-26 10:58 UTC by Anton-Phedorenko

2023-04-27 20:00 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/categories/service/dao/CategoryServiceImpl.java
> +        if (!eventRepository.existsByCategory(getById(id))) {
Вот так лучше перестроить

```
        if (eventRepository.existsByCategory(getById(id))) {
            throw new ConstraintForeignKeyException("The category is not empty");
        }
        
        categoryRepository.deleteById(id);
```

- избавились от отрицания `!`
- начали метод с условия выхода из метода - хорошая практика 
- избавились от лишней вложенности `else`

2023-04-27 20:04 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/categories/service/dao/CategoryServiceImpl.java
> +    public List<Category> getAll() {
Нигде не используется и это здорово! - можно смело удалить! ))

Вообще это очень опасный метод. Ну нельзя просто так давать возможность выбирать всё, а если у тебя там миллионы записей в БД?

2023-04-27 20:07 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/categories/service/dao/CategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDtoList(categoryRepository.findAll(PageRequest.of(from > 0 ? from / size : 0,
Какой такой `toCategoryDtoList` ? Зачем?

```
    @Override
    public List<CategoryDto> getByParam(Integer from, Integer size) {
        return categoryRepository.findAll(PageRequest.of(from > 0 ? from / size : 0, size))
                                 .map(CategoryMapper::toCategoryDto)
                                 .stream().collect(Collectors.toList());
    }
```

2023-04-27 20:07 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/compilation_event/model/CompilationEvent.java
> +    private Long id;
Пожалуйста отступы между полями, когда много аннотаций, всё сливается...

2023-04-27 20:08 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/compilation_event/repository/CompilationEventRepository.java
> +    @Query("select ce from CompilationEvent ce where ce.compilation.id = :compilationId")
Оформляй SQL запросы. Пиши спец. слова в верхнем регистре: `CREATE`, `FROM`, `AND`

2023-04-27 20:09 UTC, FanaticFiz commented on stats-server/stats-service/src/main/resources/schema.sql
> +    uri varchar(100),
Кажется 100 символов мало для URI

2023-04-27 20:14 UTC, FanaticFiz commented on ewm-service/src/main/resources/schema.sql
> +    id bigint generated always as identity primary key,
Примени выравнивание к этому файлу

2023-04-27 20:19 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/private_access/events/mapper/EventMapper.java
> +        event.setAnnotation(eventDtoInput.getAnnotation());
Тут же дублирование с соседним методом, все эти сет одинаковы, вынеси одинаковую часть...

2023-04-27 20:21 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/private_access/events/location/service/dao/LocationServiceImpl.java
> +    public LocationDto create(LocationDto locationDto) {
Зачем возвращаем dto, которую же и принесли сюда?
А вроде и не зачем! ))
Нигде возвращаемое и не используется, так может `void`?

2023-04-27 20:26 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/users/service/dao/UserServiceImpl.java
> +            return UserMapper.toUserDtoList(repository.findAllById(ids));
Лучше иметь один return

```
    @Override
    public List<UserDto> get(List<Long> ids, Integer from, Integer size) {
        List<User> users;
        if (ids == null) {
            users = repository.findAll(PageRequest.of(from > 0 ? from / size : 0, size)).toList();
        } else {
            users = repository.findAllById(ids);
        }

        return users.stream()
                    .map(UserMapper::toUserDto)
                    .collect(Collectors.toList());
    }
```

2023-04-27 20:29 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/users/service/dao/UserServiceImpl.java
> +        getById(id);
Есть еще вот такой метод: `ifPresentOrElse`, так для общего развития ))

```
        repository.findById(id)
                  .ifPresentOrElse(user -> repository.deleteById(id), () -> {
                      throw new ObjectExistenceException(String.format("User with id=%swas not found", id));
                  });
```

2023-04-27 20:36 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exceptions/exception/AccessException.java
> +    public AccessException(final String message) {
Все классы исключений, которые обрабатываются как `HttpStatus.CONFLICT` можно заменить одним общим `ConflictException`

2023-04-27 20:37 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exceptions/exception/ObjectExistenceException.java
> +public class ObjectExistenceException extends RuntimeException {
А это `NotFoundException` - название по коду, который будет возвращен клиенту: `HttpStatus.NOT_FOUND`

2023-04-27 20:38 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exceptions/handler/HandlerException.java
> +    public ResponseEntity<ErrorResponse> exc(ValidationException ex) {
Этот метод идентичен методу на 52 строке. 
Есть способ этого избежать, объединив классы в аннотации.

2023-04-27 20:43 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/private_access/requests/service/dao/RequestServiceImpl.java
> +                throw new AccessException(String.format("All seats for the event with id=%s are occupied.", eventId));
Можно же просто перестроить фразу, чтобы не пользоваться форматером
`throw new AccessException("All seats are occupied for the event with id=" + eventId);`

2023-04-27 20:44 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/compilations/service/dao/CompilationServiceImpl.java
> +                for (Event event : newEvents) {
Кол-во циклов зашкаливает, я присмотрюсь к этому месту со второго захода ))

2023-04-28 07:15 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/admin_access/categories/service/dao/CategoryServiceImpl.java
> +        if (!eventRepository.existsByCategory(getById(id))) {
сделал

2023-04-28 07:16 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/admin_access/categories/service/dao/CategoryServiceImpl.java
> +    public List<Category> getAll() {
да, уже на прошлых проектах обсуждали этот момент)

2023-04-29 08:07 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/private_access/events/mapper/EventMapper.java
> +        event.setAnnotation(eventDtoInput.getAnnotation());
сделал

2023-04-29 08:08 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/private_access/events/location/service/dao/LocationServiceImpl.java
> +    public LocationDto create(LocationDto locationDto) {
хорошо)

2023-04-29 09:16 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/exceptions/exception/AccessException.java
> +    public AccessException(final String message) {
Если позволишь, можно это оставить, потому что мне кажется каждое исключение обрабатывает свою задачу)

2023-04-29 09:16 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/exceptions/handler/HandlerException.java
> +    public ResponseEntity<ErrorResponse> exc(ValidationException ex) {
хорошо)

2023-04-29 09:30 UTC, Anton-Phedorenko commented on ewm-service/src/main/java/ru/practicum/private_access/requests/service/dao/RequestServiceImpl.java
> +                throw new AccessException(String.format("All seats for the event with id=%s are occupied.", eventId));
хорошо

2023-04-29 09:43 UTC, Anton-Phedorenko commented
Привет ,Денис! Поправил замечания, отправляю проект на проверку)

2023-04-30 07:54 UTC, FanaticFiz requested changes

2023-04-30 07:54 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/private_access/requests/service/dao/RequestServiceImpl.java
> +    public RequestDtoOutput create(Long userId, Long eventId) {
Давай еще раз, на этом примере, проведем рефакторинг.

- избавимся от лишней вложенности
- будем следовать практике: начинаем метод с условий выхода
- из репозитория (метод getByEventIdAndUserId) возвращается `Optional`

```
    @Transactional
    @Override
    public RequestDtoOutput create(Long userId, Long eventId) {
        Event event = eventService.getById(eventId);
        if (!event.getState().equals(PUBLISHED)) {
            throw new AccessException("Event is not published");
        }

        User user = userService.getById(userId);
        if (event.getUser().getId().equals(userId)) {
            throw new InvalidRequestException(String
                    .format("The user with id=%s is the initiator of the event with id=%s", userId, event.getId()));
        }

        repository.getByEventIdAndUserId(eventId, userId).ifPresent(request -> {
            throw new DuplicateException("Request already exists");
        });

        List<Event> events = new ArrayList<>();
        events.add(event);
        List<Request> requests = repository.getPendingRequests(events);
        if (!requests.isEmpty() && requests.size() >= event.getParticipantLimit()) {
            throw new AccessException("All seats are occupied for the event with id=" + eventId);
        }

        Request request = new Request();
        request.setUser(user);
        request.setEvent(event);
        request.setStatus(PENDING);
        request.setCreated(now().withNano(0));

        return RequestMapper.toRequestDto(repository.save(request));
    }        
```

Преимущество следования таким практикам в том, что тебе гораздо легче будет манипулировать кодом, выносить проверки куда-то - отрывать их от основного кода. Код не переплетен условиями, он линеен.

2023-04-30 07:54 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/compilations/service/dao/CompilationServiceImpl.java
> +        Compilation compilation = compilationRepository
Итак, создание...
Не понятно почему мы сразу как только метод начался что-то сохраняем в репозиторий... потом берем сохраненный превращаем в dto и вот только тогда начинаем что то делать??
Чем был плох изначальный dto?

Ну и отрефакторить работу с событиями.
Сначала их получаем потом один `return`

```
	@Override
	@Transactional
	public CompilationDto save(NewCompilationDto compilationDto) {
		List<Event> events;
		if (compilationDto.getEvents() == null || compilationDto.getEvents().isEmpty()) {
			events = new ArrayList<>();
		} else {
			events = eventRepository.findAllById(compilationDto.getEvents());
		}

		Compilation comp = compilationRepository.save(toNewCompilation(compilationDto, events));

		return toCompilationDto(comp);
	}
```

Часть кода переедет в маппер и не будет захломлять основной код

```
	public static Compilation toNewCompilation(NewCompilationDto dto, Collection<Event> events) {
		Compilation compilation = new Compilation();
		compilation.setTitle(dto.getTitle());
		compilation.setPinned(dto.isPinned());
		compilation.setEvents(new HashSet<>(events));

		return compilation;
	}
```

2023-04-30 07:54 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/compilations/service/dao/CompilationServiceImpl.java
> +    public CompilationDtoOutput update(Long id, CompilationDtoInput compilationDtoInput) {
При обновлении тоже накручено...
Должно быть просто

- получили compilation, кинули исключение если такого нет
- обновили поля 
- сохранили и вернули

```
    @Transactional
    @Override
    public CompilationDto update(long compId, UpdateCompilationDto dto) {
        Compilation compilation = compilationRepository
                .findById(compId)
                .orElseThrow(() -> new NotFoundException("Not found compilation by id: " + compId));

        if (dto.getTitle() != null && !dto.getTitle().isBlank()) {
            compilation.setTitle(dto.getTitle());
        }
        if (dto.getPinned() != null) {
            compilation.setPinned(dto.getPinned());
        }

        if (dto.getEvents() != null && !dto.getEvents().isEmpty()) {
            List<Event> events = eventRepository.findAllById(dto.getEvents());
            compilation.setEvents(new HashSet<>(events));
        }

        compilationRepository.save(compilation);

        return toCompilationDto(compilation);
    }
```

2023-04-30 07:54 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/admin_access/compilations/service/dao/CompilationServiceImpl.java
> +    public void delete(Long id) {
```
    @Override
    @Transactional
    public void delete(long compId) {
		if (!compilationRepository.existsById(compId)) {
			throw new NotFoundException("Not found comp by id: " + compId);
		}
		
		compilationRepository.deleteById(compId);
	}
```

2023-05-03 16:13 UTC, Anton-Phedorenko commented
Привет,Денис! Поправил замечания) Не терпится приступить к заключительной части диплома)

2023-05-04 19:36 UTC, merged